name: Build and publish container

on:
  push:
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: ko-build/setup-ko@v0.8
      - run: ko build --bare
